import { pgTable, serial, integer, varchar, text, timestamp } from "drizzle-orm/pg-core";
import { estadoPublicacion } from "./enums";
import { auditColumns } from "./_audit";

/** Dominio Mundo: naciones, razas, organizaciones, familias, bestias, minerales, gremio, etc. */

export const naciones = pgTable("naciones", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  subtitulo: varchar("subtitulo"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  gobierno: varchar("gobierno"),
  capital: varchar("capital"),
  idioma: varchar("idioma"),
  poblacion: varchar("poblacion"),
  elementoFundamental: varchar("elemento_fundamental"),
  conceptoDivino: varchar("concepto_divino"),
  diosFundador: varchar("dios_fundador"),
  estadoActual: text("estado_actual"),
  estructura: text("estructura"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const razas = pgTable("razas", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  clasificacion: varchar("clasificacion"),
  subtitulo: varchar("subtitulo"),
  descripcion: text("descripcion"),
  origen: text("origen"),
  rasgosFisicos: text("rasgos_fisicos"),
  cultura: text("cultura"),
  habilidadesRasgo: text("habilidades_rasgo"),
  esperanzaVida: varchar("esperanza_vida"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const organizaciones = pgTable("organizaciones", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  tipo: varchar("tipo"),
  subtitulo: varchar("subtitulo"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  objetivo: text("objetivo"),
  fundacion: text("fundacion"),
  ideologia: text("ideologia"),
  liderazgo: text("liderazgo"),
  miembrosDestacados: text("miembros_destacados"),
  estructuraInterna: text("estructura_interna"),
  relacionFacciones: text("relacion_facciones"),
  notasAdicionales: text("notas_adicionales"),
  sede: varchar("sede"),
  estado: varchar("estado"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const familias = pgTable("familias", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  apellido: varchar("apellido"),
  subtitulo: varchar("subtitulo"),
  origen: varchar("origen"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  poderEconomico: text("poder_economico"),
  poderPolitico: text("poder_politico"),
  poderMilitar: text("poder_militar"),
  estructuraNucleo: text("estructura_nucleo"),
  circuloExtendido: text("circulo_extendido"),
  liderazgo: text("liderazgo"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const bestias = pgTable("bestias", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  subtitulo: varchar("subtitulo"),
  nivelAmenaza: varchar("nivel_amenaza"),
  descripcion: text("descripcion"),
  cicloVida: text("ciclo_vida"),
  comportamiento: text("comportamiento"),
  habitat: text("habitat"),
  recursos: text("recursos"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const minerales = pgTable("minerales", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  rareza: varchar("rareza"),
  tipo: varchar("tipo"),
  descripcion: text("descripcion"),
  propiedades: text("propiedades"),
  usos: text("usos"),
  origen: varchar("origen"),
  imagenUrl: varchar("imagen_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const gremio = pgTable("gremio", {
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  subtitulo: varchar("subtitulo"),
  lema: varchar("lema"),
  sede: varchar("sede"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  estructuraGlobal: text("estructura_global"),
  jerarquiaRangos: text("jerarquia_rangos"),
  sistemaMisiones: text("sistema_misiones"),
  principiosGenerales: text("principios_generales"),
  normasContratos: text("normas_contratos"),
  conductaAceptable: text("conducta_aceptable"),
  conductaIntolerable: text("conducta_intolerable"),
  usoFuerza: text("uso_fuerza"),
  lealtadDiscrecion: text("lealtad_discrecion"),
  principioEspadaNeutral: text("principio_espada_neutral"),
  recompensas: text("recompensas"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
});

export const lordDemonio = pgTable("lord_demonio", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  titulo: varchar("titulo"),
  dominio: varchar("dominio"),
  descripcionFisica: text("descripcion_fisica"),
  devilTrigger: text("devil_trigger"),
  historia: text("historia"),
  poderEspecial: text("poder_especial"),
  eraAparicion: varchar("era_aparicion"),
  derrotadoPor: varchar("derrotado_por"),
  estado: varchar("estado"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const armasArtefactos = pgTable("armas_artefactos", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  tipo: varchar("tipo"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  poderEspecial: text("poder_especial"),
  propietarioActual: varchar("propietario_actual"),
  propietarioId: integer("propietario_id"),
  imagenUrl: varchar("imagen_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const sistemaMonetario = pgTable("sistema_monetario", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  denominacion: varchar("denominacion"),
  descripcion: text("descripcion"),
  valorRelativo: varchar("valor_relativo"),
  imagenUrl: varchar("imagen_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});
