import { pgTable, serial, integer, varchar, text, timestamp, doublePrecision, jsonb } from "drizzle-orm/pg-core";
import { estadoPublicacion } from "./enums";
import { auditColumns } from "./_audit";

/** Dominio Mundo: naciones, razas, organizaciones, familias, bestias, minerales, gremio, etc. */

export const naciones = pgTable("naciones", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  subtitulo: varchar("subtitulo"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  gobierno: varchar("gobierno"),
  capital: varchar("capital"),
  idioma: varchar("idioma"),
  poblacion: varchar("poblacion"),
  elementoFundamental: varchar("elemento_fundamental"),
  conceptoDivino: varchar("concepto_divino"),
  diosFundador: varchar("dios_fundador"),
  estadoActual: text("estado_actual"),
  estructura: text("estructura"),
  // Clima / geografía (§overhaul mundo).
  clima: varchar("clima"),
  terreno: varchar("terreno"),
  recursosNaturales: text("recursos_naturales"),
  // Medidores de poder 0-100 (radar comparativo).
  poderMilitarNivel: integer("poder_militar_nivel"),
  poderEconomicoNivel: integer("poder_economico_nivel"),
  poderPoliticoNivel: integer("poder_politico_nivel"),
  poderMagicoNivel: integer("poder_magico_nivel"),
  poderTecnologicoNivel: integer("poder_tecnologico_nivel"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  // Geometría en el mapa (§10): contorno y centro normalizados 0..1.
  poligono: jsonb("poligono").$type<[number, number][]>(),
  centroX: doublePrecision("centro_x"),
  centroY: doublePrecision("centro_y"),
  color: varchar("color"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const razas = pgTable("razas", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  clasificacion: varchar("clasificacion"),
  afinidad: varchar("afinidad"),
  subtitulo: varchar("subtitulo"),
  descripcion: text("descripcion"),
  origen: text("origen"),
  rasgosFisicos: text("rasgos_fisicos"),
  cultura: text("cultura"),
  habilidadesRasgo: text("habilidades_rasgo"),
  esperanzaVida: varchar("esperanza_vida"),
  // Linaje: sub-razas / variantes (auto-referencia, como magia_fundamentos).
  razaPadreId: integer("raza_padre_id"),
  // Atributos raciales 0-100 (medidores).
  statLongevidad: integer("stat_longevidad"),
  statAfinidadMagica: integer("stat_afinidad_magica"),
  statFuerza: integer("stat_fuerza"),
  statAgilidad: integer("stat_agilidad"),
  statAdaptabilidad: integer("stat_adaptabilidad"),
  // Demografía.
  poblacionEstimada: varchar("poblacion_estimada"),
  statDispersion: integer("stat_dispersion"),
  statPurezaLinaje: integer("stat_pureza_linaje"),
  // Sociedad / costumbres.
  estructuraSocial: text("estructura_social"),
  creencias: text("creencias"),
  relacionOtrasRazas: text("relacion_otras_razas"),
  // Anatomía / biología.
  dieta: varchar("dieta"),
  reproduccion: text("reproduccion"),
  rasgosDistintivos: text("rasgos_distintivos"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const organizaciones = pgTable("organizaciones", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  tipo: varchar("tipo"),
  subtitulo: varchar("subtitulo"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  objetivo: text("objetivo"),
  fundacion: text("fundacion"),
  ideologia: text("ideologia"),
  liderazgo: text("liderazgo"),
  miembrosDestacados: text("miembros_destacados"),
  estructuraInterna: text("estructura_interna"),
  relacionFacciones: text("relacion_facciones"),
  notasAdicionales: text("notas_adicionales"),
  sede: varchar("sede"),
  estado: varchar("estado"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const familias = pgTable("familias", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  apellido: varchar("apellido"),
  subtitulo: varchar("subtitulo"),
  origen: varchar("origen"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  poderEconomico: text("poder_economico"),
  poderPolitico: text("poder_politico"),
  poderMilitar: text("poder_militar"),
  poderEconomicoNivel: integer("poder_economico_nivel"),
  poderPoliticoNivel: integer("poder_politico_nivel"),
  poderMilitarNivel: integer("poder_militar_nivel"),
  estructuraNucleo: text("estructura_nucleo"),
  circuloExtendido: text("circulo_extendido"),
  liderazgo: text("liderazgo"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const bestias = pgTable("bestias", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  subtitulo: varchar("subtitulo"),
  nivelAmenaza: varchar("nivel_amenaza"),
  descripcion: text("descripcion"),
  cicloVida: text("ciclo_vida"),
  comportamiento: text("comportamiento"),
  habitat: text("habitat"),
  recursos: text("recursos"),
  // Taxonomía.
  categoria: varchar("categoria"),
  dieta: varchar("dieta"),
  tamano: varchar("tamano"),
  // Stats de combate 0-100.
  statFuerza: integer("stat_fuerza"),
  statVelocidad: integer("stat_velocidad"),
  statResistencia: integer("stat_resistencia"),
  statPoderMagico: integer("stat_poder_magico"),
  // Stats de bestiario 0-100.
  statPeligrosidad: integer("stat_peligrosidad"),
  statRareza: integer("stat_rareza"),
  statTerritorialidad: integer("stat_territorialidad"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const minerales = pgTable("minerales", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  rareza: varchar("rareza"),
  tipo: varchar("tipo"),
  descripcion: text("descripcion"),
  propiedades: text("propiedades"),
  usos: text("usos"),
  origen: varchar("origen"),
  // Afinidad elemental (slug del catálogo unificado).
  elemento: varchar("elemento"),
  // Stats de gema 0-100.
  statDureza: integer("stat_dureza"),
  statPureza: integer("stat_pureza"),
  statConductividad: integer("stat_conductividad"),
  // Stats económicos 0-100.
  statRareza: integer("stat_rareza"),
  statValor: integer("stat_valor"),
  statDemanda: integer("stat_demanda"),
  statAbundancia: integer("stat_abundancia"),
  // Valor monetario concreto (enlace al sistema monetario).
  valorMonedaId: integer("valor_moneda_id"),
  valorCantidad: doublePrecision("valor_cantidad"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const gremio = pgTable("gremio", {
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  subtitulo: varchar("subtitulo"),
  lema: varchar("lema"),
  sede: varchar("sede"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  estructuraGlobal: text("estructura_global"),
  jerarquiaRangos: text("jerarquia_rangos"),
  sistemaMisiones: text("sistema_misiones"),
  principiosGenerales: text("principios_generales"),
  normasContratos: text("normas_contratos"),
  conductaAceptable: text("conducta_aceptable"),
  conductaIntolerable: text("conducta_intolerable"),
  usoFuerza: text("uso_fuerza"),
  lealtadDiscrecion: text("lealtad_discrecion"),
  principioEspadaNeutral: text("principio_espada_neutral"),
  recompensas: text("recompensas"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
});

export const lordDemonio = pgTable("lord_demonio", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  titulo: varchar("titulo"),
  dominio: varchar("dominio"),
  descripcionFisica: text("descripcion_fisica"),
  devilTrigger: text("devil_trigger"),
  historia: text("historia"),
  poderEspecial: text("poder_especial"),
  eraAparicion: varchar("era_aparicion"),
  derrotadoPor: varchar("derrotado_por"),
  estado: varchar("estado"),
  imagenUrl: varchar("imagen_url"),
  bannerUrl: varchar("banner_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const armasArtefactos = pgTable("armas_artefactos", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  tipo: varchar("tipo"),
  descripcion: text("descripcion"),
  historia: text("historia"),
  poderEspecial: text("poder_especial"),
  propietarioActual: varchar("propietario_actual"),
  propietarioId: integer("propietario_id"),
  imagenUrl: varchar("imagen_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});

export const sistemaMonetario = pgTable("sistema_monetario", {
  ...auditColumns(),
  id: serial("id").primaryKey(),
  nombre: varchar("nombre").notNull(),
  denominacion: varchar("denominacion"),
  descripcion: text("descripcion"),
  valorRelativo: varchar("valor_relativo"),
  imagenUrl: varchar("imagen_url"),
  estadoPublicacion: estadoPublicacion("estado_publicacion").notNull().default("borrador"),
  publicadoPrimeraVezEn: timestamp("publicado_primera_vez_en", { mode: "date" }),
});
